const ActionTypes = {
    LOAD_CART_REQUEST: "LOAD_CART_REQUEST",

    LOAD_CART_SUCCESS: "LOAD_CART_SUCCESS",
    ADD_CART_SUCCESS: "ADD_CART_SUCCESS",
    UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
    DELETE_CART_SUCCESS: "DELETE_CART_SUCCESS",

    ADD_CART_REQUEST: "ADD_CART_REQUEST",
    UPDATE_CART_REQUEST: "UPDATE_CART_REQUEST",
    DELETE_CART_REQUEST: "DELETE_CART_REQUEST",

    LOAD_CART_FAIL: "LOAD_CART_FAIL",
    ADD_CART_FAIL: "ADD_CART_FAIL",
    UPDATE_CART_FAIL: "UPDATE_CART_FAIL",
    DELETE_CART_FAIL: "DELETE_CART_FAIL",

    LOAD_PRODUCTS_REQUEST: "LOAD_PRODUCTS_REQUEST",
    LOAD_PRODUCTS: "LOAD_PRODUCTS",
    LOAD_PRODUCTS_SUCCESS: "LOAD_PRODUCTS_SUCCESS",
    LOAD_PRODUCTS_FAIL: "LOAD_PRODUCTS_FAIL",

    LOAD_PRODUCT_SUCCESS: "LOAD_PRODUCT_SUCCESS",
    LOAD_PRODUCT: "LOAD_PRODUCT",
    LOAD_PRODUCT_SUCCESS: "LOAD_PRODUCT_SUCCESS",
    LOAD_PRODUCT_FAIL: "LOAD_PRODUCT_FAIL",

    LOAD_SELECTED_PRODUCT_REQUEST: "LOAD_SELECTED_PRODUCT_REQUEST",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

    LOGIN: "LOGIN",
    REGISTER: "REGISTER",
    LOGIN_REQUEST: "LOGIN_REQUEST",
    REGISTER_REQUEST: "REGISTER_REQUEST",

    LOAD_USER_REQUEST: "LOAD_USER_REQUEST",

    LOAD_CART: "LOAD_CART",
    ADD_CART: "ADD_CART",
    UPDATE_CART: "UPDATE_CART",
    DELETE_CART: "DELETE_CART",


    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    LOGOUT: "LOGOUT",

    LOGIN_FAIL: "LOGIN_FAIL",
    REGISTER_FAIL: "REGISTER_FAIL",


    CHANGE_THEME: "CHANGE_THEME",

    

}

export default ActionTypes;